[package]
name = "small-app"
version = "1.0.1"
authors = ["dystroy <denys.seguret@gmail.com>"]
edition = "2018"
description = "An example for cli-log"
license = "MIT"
readme = "README.md"

[dependencies]
cli-log = { path = "../.." }
log = "0.4"
